# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Vansh/vck/NN_on_FPGA/autoencoder/autoencoder.srcs/sources_1/ip/snr_mult/snr_mult.xci
# IP: The module: 'snr_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Vansh/vck/NN_on_FPGA/autoencoder/autoencoder.gen/sources_1/ip/snr_mult/snr_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'snr_mult'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Vansh/vck/NN_on_FPGA/autoencoder/autoencoder.srcs/sources_1/ip/snr_mult/snr_mult.xci
# IP: The module: 'snr_mult' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Vansh/vck/NN_on_FPGA/autoencoder/autoencoder.gen/sources_1/ip/snr_mult/snr_mult_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'snr_mult'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
