// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module decoder_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        data_0_val,
        data_1_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage7;
reg    ap_block_pp0_stage7_subdone;
reg   [15:0] reg_501;
wire    ap_block_pp0_stage0_11001;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_11001;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_11001;
reg   [15:0] reg_505;
reg   [15:0] reg_509;
wire    ap_block_pp0_stage7_11001;
reg   [15:0] reg_513;
reg   [15:0] reg_517;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_11001;
wire  signed [25:0] sext_ln70_fu_521_p1;
reg  signed [25:0] sext_ln70_reg_876;
reg   [15:0] trunc_ln42_4_reg_884;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
reg   [15:0] trunc_ln42_5_reg_889;
reg   [15:0] trunc_ln42_6_reg_894;
reg   [15:0] trunc_ln42_7_reg_899;
reg   [15:0] trunc_ln42_8_reg_904;
reg   [15:0] trunc_ln42_10_reg_909;
reg   [15:0] trunc_ln42_11_reg_914;
reg   [15:0] trunc_ln42_12_reg_919;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
reg   [15:0] trunc_ln42_13_reg_924;
reg   [15:0] trunc_ln42_14_reg_929;
reg   [15:0] trunc_ln42_15_reg_934;
reg  signed [15:0] data_1_val_read_reg_939;
wire  signed [25:0] sext_ln70_46_fu_529_p1;
reg  signed [25:0] sext_ln70_46_reg_945;
reg   [15:0] trunc_ln42_16_reg_953;
reg   [15:0] trunc_ln42_18_reg_958;
reg   [15:0] trunc_ln42_19_reg_963;
wire   [15:0] add_ln58_274_fu_583_p2;
reg   [15:0] add_ln58_274_reg_968;
wire   [15:0] add_ln58_256_fu_594_p2;
reg   [15:0] add_ln58_256_reg_973;
wire   [15:0] add_ln58_258_fu_606_p2;
reg   [15:0] add_ln58_258_reg_978;
wire   [15:0] add_ln58_260_fu_617_p2;
reg   [15:0] add_ln58_260_reg_983;
wire   [15:0] add_ln58_262_fu_628_p2;
reg   [15:0] add_ln58_262_reg_988;
reg   [14:0] trunc_ln42_s_reg_993;
wire   [15:0] add_ln58_264_fu_654_p2;
reg   [15:0] add_ln58_264_reg_998;
wire   [15:0] add_ln58_266_fu_665_p2;
reg   [15:0] add_ln58_266_reg_1003;
wire   [15:0] add_ln58_268_fu_676_p2;
reg   [15:0] add_ln58_268_reg_1008;
wire   [15:0] add_ln58_270_fu_687_p2;
reg   [15:0] add_ln58_270_reg_1013;
reg   [12:0] trunc_ln42_30_reg_1018;
wire   [15:0] add_ln58_272_fu_715_p2;
reg   [15:0] add_ln58_272_reg_1023;
wire   [15:0] add_ln58_276_fu_726_p2;
reg   [15:0] add_ln58_276_reg_1028;
wire   [15:0] add_ln58_278_fu_737_p2;
reg   [15:0] add_ln58_278_reg_1033;
wire   [15:0] add_ln58_280_fu_748_p2;
reg   [15:0] add_ln58_280_reg_1038;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage0_subdone;
reg   [15:0] ap_port_reg_data_1_val;
reg  signed [15:0] grp_fu_148_p0;
reg  signed [12:0] grp_fu_148_p1;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage3;
wire    ap_block_pp0_stage4;
wire    ap_block_pp0_stage5;
wire    ap_block_pp0_stage6;
wire    ap_block_pp0_stage7;
reg  signed [15:0] grp_fu_149_p0;
reg  signed [11:0] grp_fu_149_p1;
reg  signed [15:0] grp_fu_150_p0;
wire  signed [24:0] sext_ln70_45_fu_634_p1;
reg  signed [12:0] grp_fu_150_p1;
reg  signed [15:0] grp_fu_151_p0;
wire  signed [22:0] sext_ln70_44_fu_692_p1;
reg  signed [12:0] grp_fu_151_p1;
wire   [25:0] grp_fu_149_p2;
wire   [25:0] grp_fu_151_p2;
wire   [25:0] grp_fu_148_p2;
wire   [25:0] grp_fu_150_p2;
wire  signed [15:0] sext_ln70_46_fu_529_p0;
wire  signed [15:0] tmp_fu_537_p1;
wire   [23:0] tmp_fu_537_p3;
wire  signed [15:0] tmp_87_fu_549_p1;
wire   [18:0] tmp_87_fu_549_p3;
wire  signed [25:0] sext_ln73_fu_545_p1;
wire  signed [25:0] sext_ln73_25_fu_557_p1;
wire   [25:0] add_ln73_fu_561_p2;
wire   [15:0] trunc_ln42_25_fu_567_p4;
wire   [15:0] add_ln58_273_fu_577_p2;
wire   [15:0] add_ln58_fu_589_p2;
wire   [15:0] add_ln58_257_fu_600_p2;
wire   [15:0] add_ln58_259_fu_612_p2;
wire   [15:0] add_ln58_261_fu_623_p2;
wire   [24:0] trunc_ln42_s_fu_638_p1;
wire   [15:0] add_ln58_263_fu_648_p2;
wire   [15:0] add_ln58_265_fu_659_p2;
wire   [15:0] add_ln58_267_fu_670_p2;
wire   [15:0] add_ln58_269_fu_681_p2;
wire   [22:0] trunc_ln42_30_fu_699_p1;
wire   [15:0] add_ln58_271_fu_709_p2;
wire   [15:0] add_ln58_275_fu_720_p2;
wire   [15:0] add_ln58_277_fu_731_p2;
wire  signed [15:0] sext_ln42_fu_696_p1;
wire   [15:0] add_ln58_279_fu_742_p2;
wire   [15:0] add_ln58_281_fu_756_p2;
wire   [15:0] add_ln58_283_fu_767_p2;
wire  signed [13:0] sext_ln58_fu_753_p1;
wire   [13:0] add_ln58_285_fu_778_p2;
wire  signed [15:0] sext_ln58_3_fu_784_p1;
wire   [15:0] add_ln58_282_fu_762_p2;
wire   [15:0] add_ln58_284_fu_773_p2;
wire   [15:0] add_ln58_286_fu_788_p2;
reg   [7:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0_1to1;
reg    ap_block_pp0_stage1_subdone;
reg    ap_block_pp0_stage2_subdone;
reg    ap_block_pp0_stage3_subdone;
reg    ap_block_pp0_stage4_subdone;
reg    ap_block_pp0_stage5_subdone;
reg    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

decoder_mul_16s_13s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13s_26_1_1_U1(
    .din0(grp_fu_148_p0),
    .din1(grp_fu_148_p1),
    .dout(grp_fu_148_p2)
);

decoder_mul_16s_12s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 26 ))
mul_16s_12s_26_1_1_U2(
    .din0(grp_fu_149_p0),
    .din1(grp_fu_149_p1),
    .dout(grp_fu_149_p2)
);

decoder_mul_16s_13s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13s_26_1_1_U3(
    .din0(grp_fu_150_p0),
    .din1(grp_fu_150_p1),
    .dout(grp_fu_150_p2)
);

decoder_mul_16s_13s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 26 ))
mul_16s_13s_26_1_1_U4(
    .din0(grp_fu_151_p0),
    .din1(grp_fu_151_p1),
    .dout(grp_fu_151_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_ce))) begin
        add_ln58_256_reg_973 <= add_ln58_256_fu_594_p2;
        add_ln58_258_reg_978 <= add_ln58_258_fu_606_p2;
        add_ln58_260_reg_983 <= add_ln58_260_fu_617_p2;
        add_ln58_262_reg_988 <= add_ln58_262_fu_628_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b1 == ap_ce))) begin
        add_ln58_264_reg_998 <= add_ln58_264_fu_654_p2;
        add_ln58_266_reg_1003 <= add_ln58_266_fu_665_p2;
        add_ln58_268_reg_1008 <= add_ln58_268_fu_676_p2;
        add_ln58_270_reg_1013 <= add_ln58_270_fu_687_p2;
        trunc_ln42_s_reg_993 <= {{trunc_ln42_s_fu_638_p1[24:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        add_ln58_272_reg_1023 <= add_ln58_272_fu_715_p2;
        add_ln58_276_reg_1028 <= add_ln58_276_fu_726_p2;
        add_ln58_278_reg_1033 <= add_ln58_278_fu_737_p2;
        add_ln58_280_reg_1038 <= add_ln58_280_fu_748_p2;
        trunc_ln42_30_reg_1018 <= {{trunc_ln42_30_fu_699_p1[22:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        add_ln58_274_reg_968 <= add_ln58_274_fu_583_p2;
        data_1_val_read_reg_939 <= ap_port_reg_data_1_val;
        sext_ln70_46_reg_945 <= sext_ln70_46_fu_529_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_port_reg_data_1_val <= data_1_val;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_501 <= {{grp_fu_149_p2[25:10]}};
        reg_505 <= {{grp_fu_151_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage7)))) begin
        reg_509 <= {{grp_fu_148_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage5_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b1 == ap_ce)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage7)))) begin
        reg_513 <= {{grp_fu_150_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_517 <= {{grp_fu_151_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sext_ln70_reg_876 <= sext_ln70_fu_521_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        trunc_ln42_10_reg_909 <= {{grp_fu_148_p2[25:10]}};
        trunc_ln42_11_reg_914 <= {{grp_fu_150_p2[25:10]}};
        trunc_ln42_8_reg_904 <= {{grp_fu_149_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        trunc_ln42_12_reg_919 <= {{grp_fu_149_p2[25:10]}};
        trunc_ln42_13_reg_924 <= {{grp_fu_151_p2[25:10]}};
        trunc_ln42_14_reg_929 <= {{grp_fu_148_p2[25:10]}};
        trunc_ln42_15_reg_934 <= {{grp_fu_150_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        trunc_ln42_16_reg_953 <= {{grp_fu_149_p2[25:10]}};
        trunc_ln42_18_reg_958 <= {{grp_fu_148_p2[25:10]}};
        trunc_ln42_19_reg_963 <= {{grp_fu_150_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        trunc_ln42_4_reg_884 <= {{grp_fu_149_p2[25:10]}};
        trunc_ln42_5_reg_889 <= {{grp_fu_151_p2[25:10]}};
        trunc_ln42_6_reg_894 <= {{grp_fu_148_p2[25:10]}};
        trunc_ln42_7_reg_899 <= {{grp_fu_150_p2[25:10]}};
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        grp_fu_148_p0 = sext_ln70_46_reg_945;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_148_p0 = sext_ln70_46_fu_529_p1;
    end else if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_148_p0 = sext_ln70_reg_876;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_148_p0 = sext_ln70_fu_521_p1;
    end else begin
        grp_fu_148_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            grp_fu_148_p1 = 26'd1083;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            grp_fu_148_p1 = 26'd67108205;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            grp_fu_148_p1 = 26'd1027;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_fu_148_p1 = 26'd67107757;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_148_p1 = 26'd67107644;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_148_p1 = 26'd1196;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_148_p1 = 26'd502;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_148_p1 = 26'd67108108;
        end else begin
            grp_fu_148_p1 = 'bx;
        end
    end else begin
        grp_fu_148_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        grp_fu_149_p0 = sext_ln70_46_reg_945;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_149_p0 = sext_ln70_46_fu_529_p1;
    end else if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_149_p0 = sext_ln70_reg_876;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_149_p0 = sext_ln70_fu_521_p1;
    end else begin
        grp_fu_149_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            grp_fu_149_p1 = 26'd67108031;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            grp_fu_149_p1 = 26'd296;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_fu_149_p1 = 26'd67107649;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_149_p1 = 26'd67108187;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_149_p1 = 26'd67107924;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_149_p1 = 26'd67107667;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_149_p1 = 26'd67108415;
        end else begin
            grp_fu_149_p1 = 'bx;
        end
    end else begin
        grp_fu_149_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_150_p0 = sext_ln70_45_fu_634_p1;
    end else if ((((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        grp_fu_150_p0 = sext_ln70_46_reg_945;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_150_p0 = sext_ln70_46_fu_529_p1;
    end else if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_150_p0 = sext_ln70_reg_876;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_150_p0 = sext_ln70_fu_521_p1;
    end else begin
        grp_fu_150_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            grp_fu_150_p1 = 26'd693;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            grp_fu_150_p1 = 25'd33554298;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            grp_fu_150_p1 = 26'd1177;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_fu_150_p1 = 26'd67108008;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_150_p1 = 26'd1097;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_150_p1 = 26'd67107961;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_150_p1 = 26'd734;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_150_p1 = 26'd871;
        end else begin
            grp_fu_150_p1 = 'bx;
        end
    end else begin
        grp_fu_150_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_151_p0 = sext_ln70_44_fu_692_p1;
    end else if ((((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        grp_fu_151_p0 = sext_ln70_46_reg_945;
    end else if (((1'b0 == ap_block_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_151_p0 = sext_ln70_46_fu_529_p1;
    end else if ((((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        grp_fu_151_p0 = sext_ln70_reg_876;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_151_p0 = sext_ln70_fu_521_p1;
    end else begin
        grp_fu_151_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            grp_fu_151_p1 = 23'd38;
        end else if (((1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            grp_fu_151_p1 = 26'd67107851;
        end else if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            grp_fu_151_p1 = 26'd1277;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            grp_fu_151_p1 = 26'd1095;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            grp_fu_151_p1 = 26'd67107988;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            grp_fu_151_p1 = 26'd67108390;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_151_p1 = 26'd67107944;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_151_p1 = 26'd1139;
        end else begin
            grp_fu_151_p1 = 'bx;
        end
    end else begin
        grp_fu_151_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_256_fu_594_p2 = (add_ln58_fu_589_p2 + reg_501);

assign add_ln58_257_fu_600_p2 = (reg_517 + 16'd462);

assign add_ln58_258_fu_606_p2 = (add_ln58_257_fu_600_p2 + reg_505);

assign add_ln58_259_fu_612_p2 = (trunc_ln42_18_reg_958 + 16'd276);

assign add_ln58_260_fu_617_p2 = (add_ln58_259_fu_612_p2 + reg_509);

assign add_ln58_261_fu_623_p2 = (trunc_ln42_19_reg_963 + 16'd614);

assign add_ln58_262_fu_628_p2 = (add_ln58_261_fu_623_p2 + reg_513);

assign add_ln58_263_fu_648_p2 = (reg_501 + 16'd254);

assign add_ln58_264_fu_654_p2 = (add_ln58_263_fu_648_p2 + trunc_ln42_4_reg_884);

assign add_ln58_265_fu_659_p2 = (reg_505 + 16'd455);

assign add_ln58_266_fu_665_p2 = (add_ln58_265_fu_659_p2 + trunc_ln42_5_reg_889);

assign add_ln58_267_fu_670_p2 = (reg_509 + 16'd463);

assign add_ln58_268_fu_676_p2 = (add_ln58_267_fu_670_p2 + trunc_ln42_6_reg_894);

assign add_ln58_269_fu_681_p2 = (reg_513 + 16'd531);

assign add_ln58_270_fu_687_p2 = (add_ln58_269_fu_681_p2 + trunc_ln42_7_reg_899);

assign add_ln58_271_fu_709_p2 = (reg_501 + 16'd596);

assign add_ln58_272_fu_715_p2 = (add_ln58_271_fu_709_p2 + trunc_ln42_8_reg_904);

assign add_ln58_273_fu_577_p2 = ($signed(trunc_ln42_25_fu_567_p4) + $signed(16'd65420));

assign add_ln58_274_fu_583_p2 = (add_ln58_273_fu_577_p2 + reg_517);

assign add_ln58_275_fu_720_p2 = (reg_505 + 16'd406);

assign add_ln58_276_fu_726_p2 = (add_ln58_275_fu_720_p2 + trunc_ln42_10_reg_909);

assign add_ln58_277_fu_731_p2 = (reg_509 + 16'd471);

assign add_ln58_278_fu_737_p2 = (add_ln58_277_fu_731_p2 + trunc_ln42_11_reg_914);

assign add_ln58_279_fu_742_p2 = ($signed(sext_ln42_fu_696_p1) + $signed(16'd406));

assign add_ln58_280_fu_748_p2 = (add_ln58_279_fu_742_p2 + trunc_ln42_12_reg_919);

assign add_ln58_281_fu_756_p2 = (reg_509 + 16'd433);

assign add_ln58_282_fu_762_p2 = (add_ln58_281_fu_756_p2 + trunc_ln42_13_reg_924);

assign add_ln58_283_fu_767_p2 = ($signed(reg_513) + $signed(16'd65321));

assign add_ln58_284_fu_773_p2 = (add_ln58_283_fu_767_p2 + trunc_ln42_14_reg_929);

assign add_ln58_285_fu_778_p2 = ($signed(sext_ln58_fu_753_p1) + $signed(14'd474));

assign add_ln58_286_fu_788_p2 = ($signed(sext_ln58_3_fu_784_p1) + $signed(trunc_ln42_15_reg_934));

assign add_ln58_fu_589_p2 = (trunc_ln42_16_reg_953 + 16'd333);

assign add_ln73_fu_561_p2 = ($signed(sext_ln73_fu_545_p1) + $signed(sext_ln73_25_fu_557_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage3_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage4_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage5_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage6_subdone = (1'b0 == ap_ce);
end

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage7_subdone = (1'b0 == ap_ce);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_return_0 = add_ln58_256_reg_973;

assign ap_return_1 = add_ln58_258_reg_978;

assign ap_return_10 = add_ln58_276_reg_1028;

assign ap_return_11 = add_ln58_278_reg_1033;

assign ap_return_12 = add_ln58_280_reg_1038;

assign ap_return_13 = add_ln58_282_fu_762_p2;

assign ap_return_14 = add_ln58_284_fu_773_p2;

assign ap_return_15 = add_ln58_286_fu_788_p2;

assign ap_return_2 = add_ln58_260_reg_983;

assign ap_return_3 = add_ln58_262_reg_988;

assign ap_return_4 = add_ln58_264_reg_998;

assign ap_return_5 = add_ln58_266_reg_1003;

assign ap_return_6 = add_ln58_268_reg_1008;

assign ap_return_7 = add_ln58_270_reg_1013;

assign ap_return_8 = add_ln58_272_reg_1023;

assign ap_return_9 = add_ln58_274_reg_968;

assign sext_ln42_fu_696_p1 = $signed(trunc_ln42_s_reg_993);

assign sext_ln58_3_fu_784_p1 = $signed(add_ln58_285_fu_778_p2);

assign sext_ln58_fu_753_p1 = $signed(trunc_ln42_30_reg_1018);

assign sext_ln70_44_fu_692_p1 = data_1_val_read_reg_939;

assign sext_ln70_45_fu_634_p1 = data_1_val_read_reg_939;

assign sext_ln70_46_fu_529_p0 = ap_port_reg_data_1_val;

assign sext_ln70_46_fu_529_p1 = sext_ln70_46_fu_529_p0;

assign sext_ln70_fu_521_p1 = $signed(data_0_val);

assign sext_ln73_25_fu_557_p1 = $signed(tmp_87_fu_549_p3);

assign sext_ln73_fu_545_p1 = $signed(tmp_fu_537_p3);

assign tmp_87_fu_549_p1 = ap_port_reg_data_1_val;

assign tmp_87_fu_549_p3 = {{tmp_87_fu_549_p1}, {3'd0}};

assign tmp_fu_537_p1 = ap_port_reg_data_1_val;

assign tmp_fu_537_p3 = {{tmp_fu_537_p1}, {8'd0}};

assign trunc_ln42_25_fu_567_p4 = {{add_ln73_fu_561_p2[25:10]}};

assign trunc_ln42_30_fu_699_p1 = grp_fu_151_p2;

assign trunc_ln42_s_fu_638_p1 = grp_fu_150_p2;

endmodule //decoder_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s
