@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Fri Jul 26 18:13:34 +0530 2024
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab --incr --debug typical --relax --mt 2 -L xil_defaultlib -L xbip_utils_v3_0_13 -L xbip_pipe_v3_0_9 -L xbip_bram18k_v3_0_9 -L mult_gen_v12_0_21 -L axis_infrastructure_v1_1_1 -L axis_data_fifo_v2_0_13 -L lib_cdc_v1_0_3 -L proc_sys_reset_v5_0_15 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot autoencoder_tb_behav xil_defaultlib.autoencoder_tb xil_defaultlib.glbl -log elaborate.log"
call xelab  --incr --debug typical --relax --mt 2 -L xil_defaultlib -L xbip_utils_v3_0_13 -L xbip_pipe_v3_0_9 -L xbip_bram18k_v3_0_9 -L mult_gen_v12_0_21 -L axis_infrastructure_v1_1_1 -L axis_data_fifo_v2_0_13 -L lib_cdc_v1_0_3 -L proc_sys_reset_v5_0_15 -L uvm -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot autoencoder_tb_behav xil_defaultlib.autoencoder_tb xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
