# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Vansh/vck/NN_on_FPGA/autoencoder/autoencoder.srcs/sources_1/bd/autoencoder/ip/autoencoder_AWGN_adder_0_0/autoencoder_AWGN_adder_0_0.xci
# IP: The module: 'autoencoder_AWGN_adder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/Vansh/vck/NN_on_FPGA/autoencoder/autoencoder.srcs/sources_1/ip/snr_mult/snr_mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snr_mult || ORIG_REF_NAME==snr_mult} -quiet] -quiet

# XDC: c:/Users/Vansh/vck/NN_on_FPGA/autoencoder/autoencoder.gen/sources_1/bd/autoencoder/ip/autoencoder_AWGN_adder_0_0/autoencoder_AWGN_adder_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'autoencoder_AWGN_adder_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Vansh/vck/NN_on_FPGA/autoencoder/autoencoder.srcs/sources_1/bd/autoencoder/ip/autoencoder_AWGN_adder_0_0/autoencoder_AWGN_adder_0_0.xci
# IP: The module: 'autoencoder_AWGN_adder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/Vansh/vck/NN_on_FPGA/autoencoder/autoencoder.srcs/sources_1/ip/snr_mult/snr_mult.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==snr_mult || ORIG_REF_NAME==snr_mult} -quiet] -quiet

# XDC: c:/Users/Vansh/vck/NN_on_FPGA/autoencoder/autoencoder.gen/sources_1/bd/autoencoder/ip/autoencoder_AWGN_adder_0_0/autoencoder_AWGN_adder_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'autoencoder_AWGN_adder_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
