-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity decoder_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_5_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_6_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_7_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_8_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_9_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_10_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_11_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_12_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_13_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_14_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_15_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of decoder_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config3_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln45_fu_208_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_15_fu_204_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_fu_214_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_1_fu_226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_14_fu_200_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_1_fu_232_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_2_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_13_fu_196_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_2_fu_250_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_3_fu_262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_12_fu_192_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_3_fu_268_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_4_fu_280_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_11_fu_188_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_4_fu_286_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_5_fu_298_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_10_fu_184_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_5_fu_304_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_6_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_9_fu_180_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_6_fu_322_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_7_fu_334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_8_fu_176_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_7_fu_340_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_8_fu_352_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_7_fu_172_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_8_fu_358_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_9_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_6_fu_168_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_9_fu_376_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_10_fu_388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_5_fu_164_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_10_fu_394_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_11_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_4_fu_160_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_11_fu_412_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_12_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_3_fu_156_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_12_fu_430_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_13_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_2_fu_152_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_13_fu_448_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_14_fu_460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_1_fu_148_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_14_fu_466_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_15_fu_478_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln42_fu_144_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_15_fu_484_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln45_fu_222_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_1_fu_240_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_2_fu_258_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_3_fu_276_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_4_fu_294_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_5_fu_312_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_6_fu_330_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_7_fu_348_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_8_fu_366_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_9_fu_384_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_10_fu_402_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_11_fu_420_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_12_fu_438_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_13_fu_456_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_14_fu_474_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_15_fu_492_p1 : STD_LOGIC_VECTOR (15 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= zext_ln45_fu_222_p1;
    ap_return_1 <= zext_ln45_1_fu_240_p1;
    ap_return_10 <= zext_ln45_10_fu_402_p1;
    ap_return_11 <= zext_ln45_11_fu_420_p1;
    ap_return_12 <= zext_ln45_12_fu_438_p1;
    ap_return_13 <= zext_ln45_13_fu_456_p1;
    ap_return_14 <= zext_ln45_14_fu_474_p1;
    ap_return_15 <= zext_ln45_15_fu_492_p1;
    ap_return_2 <= zext_ln45_2_fu_258_p1;
    ap_return_3 <= zext_ln45_3_fu_276_p1;
    ap_return_4 <= zext_ln45_4_fu_294_p1;
    ap_return_5 <= zext_ln45_5_fu_312_p1;
    ap_return_6 <= zext_ln45_6_fu_330_p1;
    ap_return_7 <= zext_ln45_7_fu_348_p1;
    ap_return_8 <= zext_ln45_8_fu_366_p1;
    ap_return_9 <= zext_ln45_9_fu_384_p1;
    datareg_10_fu_394_p3 <= 
        trunc_ln42_5_fu_164_p1 when (icmp_ln45_10_fu_388_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_11_fu_412_p3 <= 
        trunc_ln42_4_fu_160_p1 when (icmp_ln45_11_fu_406_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_12_fu_430_p3 <= 
        trunc_ln42_3_fu_156_p1 when (icmp_ln45_12_fu_424_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_13_fu_448_p3 <= 
        trunc_ln42_2_fu_152_p1 when (icmp_ln45_13_fu_442_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_14_fu_466_p3 <= 
        trunc_ln42_1_fu_148_p1 when (icmp_ln45_14_fu_460_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_15_fu_484_p3 <= 
        trunc_ln42_fu_144_p1 when (icmp_ln45_15_fu_478_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_1_fu_232_p3 <= 
        trunc_ln42_14_fu_200_p1 when (icmp_ln45_1_fu_226_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_2_fu_250_p3 <= 
        trunc_ln42_13_fu_196_p1 when (icmp_ln45_2_fu_244_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_3_fu_268_p3 <= 
        trunc_ln42_12_fu_192_p1 when (icmp_ln45_3_fu_262_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_4_fu_286_p3 <= 
        trunc_ln42_11_fu_188_p1 when (icmp_ln45_4_fu_280_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_5_fu_304_p3 <= 
        trunc_ln42_10_fu_184_p1 when (icmp_ln45_5_fu_298_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_6_fu_322_p3 <= 
        trunc_ln42_9_fu_180_p1 when (icmp_ln45_6_fu_316_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_7_fu_340_p3 <= 
        trunc_ln42_8_fu_176_p1 when (icmp_ln45_7_fu_334_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_8_fu_358_p3 <= 
        trunc_ln42_7_fu_172_p1 when (icmp_ln45_8_fu_352_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_9_fu_376_p3 <= 
        trunc_ln42_6_fu_168_p1 when (icmp_ln45_9_fu_370_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_fu_214_p3 <= 
        trunc_ln42_15_fu_204_p1 when (icmp_ln45_fu_208_p2(0) = '1') else 
        ap_const_lv15_0;
    icmp_ln45_10_fu_388_p2 <= "1" when (signed(data_10_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_11_fu_406_p2 <= "1" when (signed(data_11_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_12_fu_424_p2 <= "1" when (signed(data_12_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_13_fu_442_p2 <= "1" when (signed(data_13_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_14_fu_460_p2 <= "1" when (signed(data_14_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_15_fu_478_p2 <= "1" when (signed(data_15_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_1_fu_226_p2 <= "1" when (signed(data_1_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_2_fu_244_p2 <= "1" when (signed(data_2_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_3_fu_262_p2 <= "1" when (signed(data_3_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_4_fu_280_p2 <= "1" when (signed(data_4_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_5_fu_298_p2 <= "1" when (signed(data_5_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_6_fu_316_p2 <= "1" when (signed(data_6_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_7_fu_334_p2 <= "1" when (signed(data_7_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_8_fu_352_p2 <= "1" when (signed(data_8_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_9_fu_370_p2 <= "1" when (signed(data_9_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_fu_208_p2 <= "1" when (signed(data_0_val) > signed(ap_const_lv16_0)) else "0";
    trunc_ln42_10_fu_184_p1 <= data_5_val(15 - 1 downto 0);
    trunc_ln42_11_fu_188_p1 <= data_4_val(15 - 1 downto 0);
    trunc_ln42_12_fu_192_p1 <= data_3_val(15 - 1 downto 0);
    trunc_ln42_13_fu_196_p1 <= data_2_val(15 - 1 downto 0);
    trunc_ln42_14_fu_200_p1 <= data_1_val(15 - 1 downto 0);
    trunc_ln42_15_fu_204_p1 <= data_0_val(15 - 1 downto 0);
    trunc_ln42_1_fu_148_p1 <= data_14_val(15 - 1 downto 0);
    trunc_ln42_2_fu_152_p1 <= data_13_val(15 - 1 downto 0);
    trunc_ln42_3_fu_156_p1 <= data_12_val(15 - 1 downto 0);
    trunc_ln42_4_fu_160_p1 <= data_11_val(15 - 1 downto 0);
    trunc_ln42_5_fu_164_p1 <= data_10_val(15 - 1 downto 0);
    trunc_ln42_6_fu_168_p1 <= data_9_val(15 - 1 downto 0);
    trunc_ln42_7_fu_172_p1 <= data_8_val(15 - 1 downto 0);
    trunc_ln42_8_fu_176_p1 <= data_7_val(15 - 1 downto 0);
    trunc_ln42_9_fu_180_p1 <= data_6_val(15 - 1 downto 0);
    trunc_ln42_fu_144_p1 <= data_15_val(15 - 1 downto 0);
    zext_ln45_10_fu_402_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_10_fu_394_p3),16));
    zext_ln45_11_fu_420_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_11_fu_412_p3),16));
    zext_ln45_12_fu_438_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_12_fu_430_p3),16));
    zext_ln45_13_fu_456_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_13_fu_448_p3),16));
    zext_ln45_14_fu_474_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_14_fu_466_p3),16));
    zext_ln45_15_fu_492_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_15_fu_484_p3),16));
    zext_ln45_1_fu_240_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_1_fu_232_p3),16));
    zext_ln45_2_fu_258_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_2_fu_250_p3),16));
    zext_ln45_3_fu_276_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_3_fu_268_p3),16));
    zext_ln45_4_fu_294_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_4_fu_286_p3),16));
    zext_ln45_5_fu_312_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_5_fu_304_p3),16));
    zext_ln45_6_fu_330_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_6_fu_322_p3),16));
    zext_ln45_7_fu_348_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_7_fu_340_p3),16));
    zext_ln45_8_fu_366_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_8_fu_358_p3),16));
    zext_ln45_9_fu_384_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_9_fu_376_p3),16));
    zext_ln45_fu_222_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_fu_214_p3),16));
end behav;
