# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Vansh/vck/NN_on_FPGA/autoencoder/autoencoder.srcs/sources_1/bd/autoencoder/ip/autoencoder_encoder_0_0/autoencoder_encoder_0_0.xci
# IP: The module: 'autoencoder_encoder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Vansh/vck/NN_on_FPGA/autoencoder/autoencoder.gen/sources_1/bd/autoencoder/ip/autoencoder_encoder_0_0/constraints/encoder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'autoencoder_encoder_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Vansh/vck/NN_on_FPGA/autoencoder/autoencoder.srcs/sources_1/bd/autoencoder/ip/autoencoder_encoder_0_0/autoencoder_encoder_0_0.xci
# IP: The module: 'autoencoder_encoder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Vansh/vck/NN_on_FPGA/autoencoder/autoencoder.gen/sources_1/bd/autoencoder/ip/autoencoder_encoder_0_0/constraints/encoder_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'autoencoder_encoder_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
